export type LinkIcon = "arrow" | "mail" | "play" | "calendar" | "phone" | "map" | "bag";
export type LinkItem = { label: string; href: string; note?: string; icon: LinkIcon };
export type ProductItem = { name: string; price: string; detail: string; image: string };
export type PublicSection =
  | { type: "links"; title?: string; items: LinkItem[] }
  | { type: "quote"; text: string; author?: string }
  | { type: "stats"; items: { value: string; label: string }[] }
  | { type: "newsletter"; title: string; copy: string }
  | { type: "products"; title: string; items: ProductItem[] }
  | { type: "hours"; title: string; items: { day: string; time: string }[] };

export type TemplateLayout = "minimal" | "creator" | "store" | "business" | "restaurant" | "services" | "luxury" | "bento";
export type PublicTemplate = {
  id: string; name: string; category: string; direction?: "rtl" | "ltr"; layout: TemplateLayout;
  theme: "sand" | "midnight" | "violet" | "paper" | "forest" | "coral" | "ocean" | "mono";
  avatar: string; title: string; handle: string; bio: string; location?: string; heroImage?: string; sections: PublicSection[];
};

const whatsapp = (message: string) => `https://wa.me/966500000000?text=${encodeURIComponent(message)}`;
const email = "mailto:hello@linka.example.com";
const image = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=80`;

export const templates: PublicTemplate[] = [
  { id: "1", name: "الحد الأدنى", category: "ملف شخصي", layout: "minimal", theme: "mono", avatar: "أ", title: "أثير الحربي", handle: "@athir.notes", bio: "أشياء قليلة أعود إليها كثيراً: قراءة جيدة، تصميم واضح، وملاحظات صادقة.", sections: [{ type: "links", items: [{ label: "ملاحظة هذا الشهر", href: "/3", icon: "arrow" }, { label: "قائمة القراءة", href: "/3", icon: "arrow" }, { label: "اكتب لي", href: email, icon: "mail" }] }, { type: "quote", text: "اختر ما يستحق البقاء، ودع الباقي يمر.", author: "أثير" }] },
  { id: "2", name: "صانع محتوى", category: "مبدعون", layout: "creator", theme: "midnight", avatar: "م", title: "مِهاد العتيبي", handle: "@mihd.film", bio: "مخرج ومصور من الرياض. أحوّل الحكايات اليومية إلى أفلام قصيرة تشبه أصحابها.", location: "الرياض، السعودية", heroImage: image("photo-1485846234645-a62644f84728"), sections: [{ type: "links", title: "شاهد الآن", items: [{ label: "الفيلم الأخير: عابر", href: "/3", note: "12:40 دقيقة", icon: "play" }, { label: "كواليس التصوير في العلا", href: "/3", note: "فيديو جديد", icon: "play" }] }, { type: "stats", items: [{ value: "٢٧", label: "فيلماً" }, { value: "٨", label: "جوائز" }, { value: "٤", label: "مدن" }] }, { type: "links", items: [{ label: "تعاون أو مشروع جديد", href: whatsapp("مرحباً مهاد، أود الاستفسار عن مشروع."), icon: "mail" }] }] },
  { id: "3", name: "متجر صغير", category: "تجارة", layout: "store", theme: "coral", avatar: "س", title: "سُلافة للأشياء الجميلة", handle: "@sulafa.goods", bio: "اختيارات صغيرة للبيت والمكتب، صُنعت لتُستخدم كل يوم وتبقى طويلاً.", heroImage: image("photo-1513519245088-0e12902e5a38"), sections: [{ type: "products", title: "وصل حديثاً", items: [{ name: "كوب الصباح", price: "٦٨ ر.س", detail: "خزف يدوي · إصدار محدود", image: image("photo-1514228742587-6b1558fcca3d") }, { name: "مفكرة يومية", price: "٤٢ ر.س", detail: "ورق معاد التدوير · ١٢٠ صفحة", image: image("photo-1531346878377-a5be20888e57") }, { name: "شمعة خشب التين", price: "٨٥ ر.س", detail: "صويا طبيعية · ٤٥ ساعة", image: image("photo-1603006905003-be475563bc59") }] }, { type: "links", items: [{ label: "اطلب عبر واتساب", href: whatsapp("مرحباً، أود الطلب من سُلافة."), note: "التوصيل داخل المملكة", icon: "bag" }] }] },
  { id: "4", name: "شركة واستشارات", category: "أعمال", layout: "business", theme: "paper", avatar: "ن", title: "نقطة بداية", handle: "nuqta.co", bio: "استوديو استراتيجية وهوية يساعد الشركات الناشئة على اتخاذ الخطوة التالية بثقة.", location: "حي الملقا، الرياض", sections: [{ type: "links", title: "ما الذي نفعله", items: [{ label: "استراتيجية العلامة", href: "/1", note: "تموضع، رسائل، وبوصلة قرار", icon: "arrow" }, { label: "هوية بصرية متكاملة", href: "/1", note: "نظام يَظهر ويعمل بوضوح", icon: "arrow" }, { label: "دراسة حالة: مساحة", href: "/1", icon: "arrow" }] }, { type: "stats", items: [{ value: "+٤٨", label: "علامة أطلقناها" }, { value: "٩٣٪", label: "عملاء بالترشيح" }] }, { type: "links", items: [{ label: "احجز جلسة تعارف", href: whatsapp("مرحباً نقطة بداية، أود حجز جلسة تعارف."), note: "٣٠ دقيقة بلا مقابل", icon: "calendar" }] }] },
  { id: "5", name: "مطعم وطلب", category: "مطاعم", layout: "restaurant", theme: "forest", avatar: "ن", title: "نَوى", handle: "nawa.kitchen", bio: "مطبخ نجدي معاصر؛ نطبخ من الذاكرة ونقدّمه بطريقتنا الخاصة.", location: "شارع التخصصي، الرياض", heroImage: image("photo-1555396273-367ea4eb4db5"), sections: [{ type: "products", title: "من قائمة اليوم", items: [{ name: "جريش نَوى", price: "٥٨ ر.س", detail: "قمح مجروش، لحم غنم، ليمون أسود", image: image("photo-1547592180-85f173990554") }, { name: "دجاج مدخّن", price: "٦٤ ر.س", detail: "أرز بسمتي، دقوس طازج", image: image("photo-1603133872878-684f208fb84b") }] }, { type: "hours", title: "ساعات العمل", items: [{ day: "السبت — الخميس", time: "١٢:٣٠ م — ١٢ ص" }, { day: "الجمعة", time: "١:٣٠ م — ١٢ ص" }] }, { type: "links", items: [{ label: "اطلب طاولتك عبر واتساب", href: whatsapp("مرحباً نَوى، أود حجز طاولة."), icon: "calendar" }, { label: "موقعنا على الخريطة", href: "https://maps.google.com/?q=24.744,46.675", icon: "map" }] }] },
  { id: "6", name: "خدمات وحجوزات", category: "خدمات", layout: "services", theme: "ocean", avatar: "د", title: "دانية العبدالله", handle: "@dania.wellbeing", bio: "أخصائية تغذية علاجية. خطط واقعية تساعدك على بناء علاقة أهدأ مع الأكل.", location: "جلسات عن بُعد وفي جدة", sections: [{ type: "links", title: "اختاري ما يناسبك", items: [{ label: "استشارة أولى", href: whatsapp("مرحباً دانية، أود حجز استشارة أولى."), note: "٦٠ دقيقة · ٣٥٠ ر.س", icon: "calendar" }, { label: "برنامج ٨ أسابيع", href: whatsapp("مرحباً دانية، أود معرفة تفاصيل برنامج ٨ أسابيع."), note: "متابعة أسبوعية وخطة شخصية", icon: "calendar" }, { label: "استشارة سريعة", href: whatsapp("مرحباً دانية، أود حجز استشارة سريعة."), note: "٣٠ دقيقة · ٢٠٠ ر.س", icon: "phone" }] }, { type: "quote", text: "الخطة الناجحة هي التي تناسب يومك الحقيقي، لا يومك المثالي.", author: "دانية" }, { type: "links", items: [{ label: "سؤال قبل الحجز", href: whatsapp("مرحباً دانية، لدي سؤال قبل الحجز."), icon: "mail" }] }] },
  { id: "7", name: "ضيافة فاخرة", category: "ضيافة", layout: "luxury", theme: "sand", avatar: "ر", title: "رِواق الساحل", handle: "riwaq.coast", bio: "فيلا هادئة على ساحل أملج؛ خصوصية كاملة، بحر قريب، ووقت لك وحدك.", location: "أملج، البحر الأحمر", heroImage: image("photo-1507525428034-b723cf961d3e"), sections: [{ type: "stats", items: [{ value: "٣", label: "أجنحة" }, { value: "٨", label: "ضيوف" }, { value: "٢٤/٧", label: "مضيف خاص" }] }, { type: "links", items: [{ label: "استكشف الإقامة", href: "/1", icon: "arrow" }, { label: "تحقق من التوفر", href: whatsapp("مرحباً رِواق الساحل، أود التحقق من التوفر."), note: "إقامات من ليلتين", icon: "calendar" }] }, { type: "quote", text: "رفاهية لا تُعلن عن نفسها، بل تشعر بها.", author: "رِواق الساحل" }] },
  { id: "8", name: "مربعات مرنة", category: "متعدد", layout: "bento", theme: "violet", avatar: "غ", title: "غرس", handle: "@ghars.community", bio: "مبادرة محلية تزرع مساحات خضراء وتجمع الجيران حول أفكار صغيرة لها أثر كبير.", location: "حي السفارات، الرياض", heroImage: image("photo-1464226184884-fa280b87c399"), sections: [{ type: "stats", items: [{ value: "١٬٢٤٠", label: "شتلة" }, { value: "١٨", label: "فعالية" }, { value: "٦", label: "أحياء" }] }, { type: "links", title: "شارك معنا", items: [{ label: "فعالية السبت القادمة", href: whatsapp("مرحباً غرس، أود الانضمام لفعالية السبت."), note: "السبت · ٤:٠٠ مساءً", icon: "calendar" }, { label: "تطوع معنا", href: whatsapp("مرحباً غرس، أود التطوع معكم."), icon: "arrow" }] }, { type: "newsletter", title: "رسالة الحي", copy: "أخبار الزراعة واللقاءات القادمة، مرة واحدة كل شهر." }] },
];

export const getTemplate = (id: string) => templates.find((template) => template.id === id);
