'use server'
import { revalidatePath } from 'next/cache'
import { z } from 'zod'
import { createClient } from '@/lib/supabase/server'
import { getCurrentProfile, getCurrentUser } from '@/lib/auth/session'
import { createPage, updatePage, togglePagePublish } from '@/lib/db/pages'
import { createSection, updateSection, deleteSection, reorderSections } from '@/lib/db/sections'
import { createLink, updateLink, deleteLink, reorderLinks } from '@/lib/db/links'
import { createProduct, updateProduct, deleteProduct, reorderProducts } from '@/lib/db/products'
import { createService, updateService, deleteService, reorderServices } from '@/lib/db/services'
const idSchema=z.string().uuid();const titleSchema=z.string().trim().min(1).max(160);const urlSchema=z.string().trim().url().refine(v=>['http:','https:'].includes(new URL(v).protocol),'Only HTTP(S) URLs are allowed');const whatsappSchema=z.string().trim().regex(/^\+?[0-9 ()-]{7,25}$/);const currencySchema=z.string().trim().regex(/^[A-Z]{3}$/);const messageSchema=z.string().trim().max(500);const sectionTypeSchema=z.enum(['links','products','services','social','media','text']);
function value(f:FormData,k:string){return String(f.get(k)??'').trim()}function optional(v:string){return v||null}function redirectAfterSave(){revalidatePath('/dashboard');revalidatePath('/dashboard/edit');revalidatePath('/[username]','page')}
async function requireOwner(){const user=await getCurrentUser();const profile=await getCurrentProfile();if(!user||!profile)throw new Error('Authentication required');return{user,profile}}
async function ensurePage(profileId:string){const s=await createClient();const{data,error}=await s.from('pages').select('id').eq('profile_id',profileId).maybeSingle();if(error)throw error;return data}
async function assertPageLimit(profileId:string,planType:string,key:string,pageId:string){const s=await createClient();const{data:plan,error}=await s.from('plans').select('limits').eq('code',planType).eq('is_active',true).maybeSingle();if(error)throw error;const limit=Number((plan?.limits as Record<string,unknown>|null)?.[key]??-1);if(limit<0)return;let count=0;if(key==='sections'){const r=await s.from('page_sections').select('*',{count:'exact',head:true}).eq('page_id',pageId);if(r.error)throw r.error;count=r.count??0}else{const{data:sections,error}=await s.from('page_sections').select('id').eq('page_id',pageId);if(error)throw error;const ids=(sections??[]).map(x=>x.id);if(ids.length){const table=key==='links'?'links':key==='products'?'products':'services';const r=await s.from(table).select('*',{count:'exact',head:true}).in('section_id',ids);if(r.error)throw r.error;count=r.count??0}}if(count>=limit)throw new Error(`Plan limit reached for ${key}`)}
export async function createPageAction(f:FormData){const{profile}=await requireOwner();const title=titleSchema.parse(value(f,'title'));const username=z.string().trim().min(3).max(30).regex(/^[a-z0-9][a-z0-9_-]{2,29}$/).parse(value(f,'username').toLowerCase());const s=await createClient();const{data:exists}=await s.from('profiles').select('id').eq('username',username).neq('id',profile.id).maybeSingle();if(exists)throw new Error('اسم المستخدم مستخدم بالفعل');const{error:pe}=await s.from('profiles').update({username}).eq('id',profile.id);if(pe)throw pe;if(!await createPage(profile.id,{title}))throw new Error('تعذر إنشاء الصفحة');redirectAfterSave()}
export async function updatePageAction(f:FormData){const{profile}=await requireOwner();const pageId=idSchema.parse(value(f,'pageId'));const title=titleSchema.parse(value(f,'title'));const bio=z.string().max(500).parse(value(f,'bio'));const avatarRaw=value(f,'avatarUrl');const seoTitle=z.string().max(160).parse(value(f,'seoTitle'));const seoDescription=z.string().max(320).parse(value(f,'seoDescription'));const avatarUrl=avatarRaw?urlSchema.parse(avatarRaw):null;const username=z.string().trim().min(3).max(30).regex(/^[a-z0-9][a-z0-9_-]{2,29}$/).parse(value(f,'username').toLowerCase());const s=await createClient();const{data:other}=await s.from('profiles').select('id').eq('username',username).neq('id',profile.id).maybeSingle();if(other)throw new Error('اسم المستخدم مستخدم بالفعل');const{error:pe}=await s.from('profiles').update({username}).eq('id',profile.id);if(pe)throw pe;const{data:current}=await s.from('pages').select('theme').eq('id',pageId).eq('profile_id',profile.id).maybeSingle();if(!current)throw new Error('Page not found');const theme=current.theme&&typeof current.theme==='object'&&!Array.isArray(current.theme)?current.theme as Record<string,unknown>:{};const page=await updatePage(profile.id,{title,bio:optional(bio),avatar_url:avatarUrl,seo_title:optional(seoTitle),seo_description:optional(seoDescription),theme});if(!page||page.id!==pageId)throw new Error('Unable to update page');redirectAfterSave()}
export async function saveDesignAction(f:FormData){const{profile}=await requireOwner();const pageId=idSchema.parse(value(f,'pageId'));const s=await createClient();const{data:page,error}=await s.from('pages').select('theme').eq('id',pageId).eq('profile_id',profile.id).maybeSingle();if(error||!page)throw error||new Error('Page not found');let patch:Record<string,unknown>;try{patch=JSON.parse(value(f,'design'))}catch{throw new Error('Invalid design')}const current=page.theme&&typeof page.theme==='object'&&!Array.isArray(page.theme)?page.theme as Record<string,unknown>:{};const{error:e}=await s.from('pages').update({theme:{...current,...patch}}).eq('id',pageId).eq('profile_id',profile.id);if(e)throw e;redirectAfterSave()}
export async function applyTemplateAction(f:FormData){const{profile}=await requireOwner();const pageId=idSchema.parse(value(f,'pageId'));const template=z.string().trim().min(1).max(20).parse(value(f,'template'));const presets:Record<string,Record<string,unknown>>={minimal:{theme:'mono',layout:'minimal'},creator:{theme:'midnight',layout:'creator'},store:{theme:'coral',layout:'store'},business:{theme:'paper',layout:'business'},restaurant:{theme:'forest',layout:'restaurant'},services:{theme:'ocean',layout:'services'},luxury:{theme:'sand',layout:'luxury'},bento:{theme:'violet',layout:'bento'}};const preset=presets[template];if(!preset)throw new Error('Template not found');const s=await createClient();const{error}=await s.from('pages').update({theme:preset}).eq('id',pageId).eq('profile_id',profile.id);if(error)throw error;redirectAfterSave()}
export async function updateLinkStyleAction(f:FormData){const{profile}=await requireOwner();const id=idSchema.parse(value(f,'linkId'));let style:Record<string,unknown>;try{style=JSON.parse(value(f,'style')||'{}')}catch{throw new Error('Invalid link style')}const imageUrl=optional(value(f,'imageUrl'));const s=await createClient();const{data}=await s.from('links').select('id,section_id,page_sections!inner(page_id)').eq('id',id).eq('page_sections.page_id',profile.id).maybeSingle();if(!data)throw new Error('Link not found');const{error}=await s.from('links').update({style,image_url:imageUrl}).eq('id',id);if(error)throw error;redirectAfterSave()}
export async function updateSectionStyleAction(f:FormData){const{profile}=await requireOwner();const id=idSchema.parse(value(f,'sectionId'));let style:Record<string,unknown>;try{style=JSON.parse(value(f,'style')||'{}')}catch{throw new Error('Invalid section style')}const s=await createClient();const page=await ensurePage(profile.id);if(!page)throw new Error('Page not found');const{data}=await s.from('page_sections').select('id').eq('id',id).eq('page_id',page.id).maybeSingle();if(!data)throw new Error('Section not found');const{error}=await s.from('page_sections').update({style}).eq('id',id);if(error)throw error;redirectAfterSave()}
export async function updateSocialStyleAction(f:FormData){const{profile}=await requireOwner();const id=idSchema.parse(value(f,'socialId'));let style:Record<string,unknown>;try{style=JSON.parse(value(f,'style')||'{}')}catch{throw new Error('Invalid social style')}const imageUrl=optional(value(f,'imageUrl'));const page=await ensurePage(profile.id);if(!page)throw new Error('Page not found');const s=await createClient();const{error}=await s.from('social_links').update({style,image_url:imageUrl}).eq('id',id).eq('page_id',page.id);if(error)throw error;redirectAfterSave()}
export async function togglePublishAction(f:FormData){const{profile}=await requireOwner();const pageId=idSchema.parse(value(f,'pageId'));const page=await togglePagePublish(profile.id);if(!page||page.id!==pageId)throw new Error('Unable to change publication status');redirectAfterSave()}
export async function addSectionAction(f:FormData){const{profile}=await requireOwner();const page=await ensurePage(profile.id);if(!page)throw new Error('Create a page first');await assertPageLimit(profile.id,profile.plan_type,'sections',page.id);const type=sectionTypeSchema.parse(value(f,'type'));const title=z.string().max(120).parse(value(f,'title'));if(!await createSection(page.id,{type,title:optional(title)}))throw new Error('Unable to create section');redirectAfterSave()}
export async function updateSectionAction(f:FormData){await requireOwner();if(!await updateSection(idSchema.parse(value(f,'sectionId')),{title:optional(z.string().max(120).parse(value(f,'title'))),is_visible:f.get('isVisible')==='on'}))throw new Error('Unable to update section');redirectAfterSave()}
export async function deleteSectionAction(f:FormData){await requireOwner();if(!await deleteSection(idSchema.parse(value(f,'sectionId'))))throw new Error('Unable to delete section');redirectAfterSave()}
export async function moveSectionAction(f:FormData){await requireOwner();const id=idSchema.parse(value(f,'sectionId'));const direction=value(f,'direction')==='up'?-1:1;const s=await createClient();const{data:item}=await s.from('page_sections').select('id,page_id,position').eq('id',id).single();if(!item)throw new Error('Section not found');const{data:target}=await s.from('page_sections').select('id,position').eq('page_id',item.page_id).eq('position',item.position+direction).maybeSingle();if(!target)return;if(!await reorderSections([{id:item.id,position:target.position},{id:target.id,position:item.position}]))throw new Error('Unable to reorder sections');redirectAfterSave()}
export async function addLinkAction(f:FormData){const{profile}=await requireOwner();const page=await ensurePage(profile.id);if(!page)throw new Error('Create a page first');await assertPageLimit(profile.id,profile.plan_type,'links',page.id);const sectionId=idSchema.parse(value(f,'sectionId'));const title=titleSchema.parse(value(f,'title'));const url=urlSchema.parse(value(f,'url'));if(!await createLink(sectionId,{title,url}))throw new Error('Unable to create link');redirectAfterSave()}
export async function updateLinkAction(f:FormData){await requireOwner();const id=idSchema.parse(value(f,'linkId'));const title=titleSchema.parse(value(f,'title'));const url=urlSchema.parse(value(f,'url'));if(!await updateLink(id,{title,url,is_visible:f.get('isVisible')==='on'}))throw new Error('Unable to update link');redirectAfterSave()}
export async function deleteLinkAction(f:FormData){await requireOwner();if(!await deleteLink(idSchema.parse(value(f,'linkId'))))throw new Error('Unable to delete link');redirectAfterSave()}
export async function moveLinkAction(f:FormData){await requireOwner();const id=idSchema.parse(value(f,'linkId'));const direction=value(f,'direction')==='up'?-1:1;const s=await createClient();const{data:item}=await s.from('links').select('id,section_id,position').eq('id',id).single();if(!item)throw new Error('Link not found');const{data:target}=await s.from('links').select('id,position').eq('section_id',item.section_id).eq('position',item.position+direction).maybeSingle();if(!target)return;if(!await reorderLinks([{id:item.id,position:target.position},{id:target.id,position:item.position}]))throw new Error('Unable to reorder links');redirectAfterSave()}
export async function addProductAction(f:FormData){const{profile}=await requireOwner();const page=await ensurePage(profile.id);if(!page)throw new Error('Create a page first');await assertPageLimit(profile.id,profile.plan_type,'products',page.id);const sectionId=idSchema.parse(value(f,'sectionId'));const name=titleSchema.parse(value(f,'name'));const description=z.string().max(2000).parse(value(f,'description'));const priceCents=z.coerce.number().int().min(0).max(100000000).parse(value(f,'priceCents'));const currency=currencySchema.parse(value(f,'currency')||'USD');const checkout=value(f,'checkoutUrl');const whatsapp=value(f,'whatsappNumber');const message=messageSchema.parse(value(f,'whatsappMessage'));const imageUrl=optional(value(f,'imageUrl'));if(!checkout&&!whatsapp)throw new Error('أضف رابط شراء أو رقم واتساب');if(checkout)urlSchema.parse(checkout);if(whatsapp)whatsappSchema.parse(whatsapp);if(!await createProduct(sectionId,{name,description:optional(description),price_cents:priceCents,currency,checkout_url:checkout||undefined,whatsapp_number:whatsapp||undefined,whatsapp_message:message||null,image_url:imageUrl}))throw new Error('تعذر إنشاء المنتج');redirectAfterSave()}
export async function updateProductAction(f:FormData){await requireOwner();const id=idSchema.parse(value(f,'productId'));const name=titleSchema.parse(value(f,'name'));const description=z.string().max(2000).parse(value(f,'description'));const priceCents=z.coerce.number().int().min(0).max(100000000).parse(value(f,'priceCents'));const currency=currencySchema.parse(value(f,'currency')||'USD');const checkout=value(f,'checkoutUrl');const whatsapp=value(f,'whatsappNumber');const message=messageSchema.parse(value(f,'whatsappMessage'));const imageUrl=optional(value(f,'imageUrl'));if(!checkout&&!whatsapp)throw new Error('أضف رابط شراء أو رقم واتساب');if(checkout)urlSchema.parse(checkout);if(whatsapp)whatsappSchema.parse(whatsapp);if(!await updateProduct(id,{name,description:optional(description),price_cents:priceCents,currency,checkout_url:checkout||null,whatsapp_number:whatsapp||null,whatsapp_message:message||null,image_url:imageUrl,is_visible:f.get('isVisible')==='on'}))throw new Error('تعذر تحديث المنتج');redirectAfterSave()}
export async function deleteProductAction(f:FormData){await requireOwner();if(!await deleteProduct(idSchema.parse(value(f,'productId'))))throw new Error('Unable to delete product');redirectAfterSave()}
export async function moveProductAction(f:FormData){await requireOwner();const id=idSchema.parse(value(f,'productId'));const direction=value(f,'direction')==='up'?-1:1;const s=await createClient();const{data:item}=await s.from('products').select('id,section_id,position').eq('id',id).single();if(!item)throw new Error('Product not found');const{data:target}=await s.from('products').select('id,position').eq('section_id',item.section_id).eq('position',item.position+direction).maybeSingle();if(!target)return;if(!await reorderProducts([{id:item.id,position:target.position},{id:target.id,position:item.position}]))throw new Error('Unable to reorder products');redirectAfterSave()}
export async function addServiceAction(f:FormData){const{profile}=await requireOwner();const page=await ensurePage(profile.id);if(!page)throw new Error('Create a page first');await assertPageLimit(profile.id,profile.plan_type,'services',page.id);const sectionId=idSchema.parse(value(f,'sectionId'));const name=titleSchema.parse(value(f,'name'));const description=z.string().max(2000).parse(value(f,'description'));const priceRaw=value(f,'priceCents');const durationRaw=value(f,'durationMinutes');const booking=value(f,'bookingUrl');const whatsapp=value(f,'whatsappNumber');const message=messageSchema.parse(value(f,'whatsappMessage'));const imageUrl=optional(value(f,'imageUrl'));if(!booking&&!whatsapp)throw new Error('أضف رابط حجز أو رقم واتساب');if(booking)urlSchema.parse(booking);if(whatsapp)whatsappSchema.parse(whatsapp);const result=await createService(sectionId,{name,description:optional(description),price_cents:priceRaw?z.coerce.number().int().min(0).max(100000000).parse(priceRaw):null,currency:currencySchema.parse(value(f,'currency')||'USD'),duration_minutes:durationRaw?z.coerce.number().int().min(1).max(1440).parse(durationRaw):null,booking_url:booking||undefined,whatsapp_number:whatsapp||undefined,whatsapp_message:message||null,image_url:imageUrl});if(!result)throw new Error('تعذر إنشاء الخدمة');redirectAfterSave()}
export async function updateServiceAction(f:FormData){await requireOwner();const id=idSchema.parse(value(f,'serviceId'));const name=titleSchema.parse(value(f,'name'));const description=z.string().max(2000).parse(value(f,'description'));const booking=value(f,'bookingUrl');const whatsapp=value(f,'whatsappNumber');const message=messageSchema.parse(value(f,'whatsappMessage'));const imageUrl=optional(value(f,'imageUrl'));if(!booking&&!whatsapp)throw new Error('أضف رابط حجز أو رقم واتساب');if(booking)urlSchema.parse(booking);if(whatsapp)whatsappSchema.parse(whatsapp);if(!await updateService(id,{name,description:optional(description),price_cents:value(f,'priceCents')?z.coerce.number().int().min(0).max(100000000).parse(value(f,'priceCents')):null,currency:currencySchema.parse(value(f,'currency')||'USD'),duration_minutes:value(f,'durationMinutes')?z.coerce.number().int().min(1).max(1440).parse(value(f,'durationMinutes')):null,booking_url:booking||null,whatsapp_number:whatsapp||null,whatsapp_message:message||null,image_url:imageUrl,is_visible:f.get('isVisible')==='on'}))throw new Error('تعذر تحديث الخدمة');redirectAfterSave()}
export async function deleteServiceAction(f:FormData){await requireOwner();if(!await deleteService(idSchema.parse(value(f,'serviceId'))))throw new Error('Unable to delete service');redirectAfterSave()}
export async function moveServiceAction(f:FormData){await requireOwner();const id=idSchema.parse(value(f,'serviceId'));const direction=value(f,'direction')==='up'?-1:1;const s=await createClient();const{data:item}=await s.from('services').select('id,section_id,position').eq('id',id).single();if(!item)throw new Error('Service not found');const{data:target}=await s.from('services').select('id,position').eq('section_id',item.section_id).eq('position',item.position+direction).maybeSingle();if(!target)return;if(!await reorderServices([{id:item.id,position:target.position},{id:target.id,position:item.position}]))throw new Error('Unable to reorder services');redirectAfterSave()}
export async function addSocialAction(f:FormData){const{profile}=await requireOwner();const page=await ensurePage(profile.id);if(!page)throw new Error('Create a page first');const platform=z.string().trim().min(2).max(40).regex(/^[a-z0-9_-]+$/).parse(value(f,'platform').toLowerCase());const url=urlSchema.parse(value(f,'url'));const s=await createClient();const{data:rows,error}=await s.from('social_links').select('position').eq('page_id',page.id).order('position',{ascending:false}).limit(1);if(error)throw error;const position=rows?.[0]?.position!=null?rows[0].position+1:0;const{error:ie}=await s.from('social_links').insert({page_id:page.id,platform,url,position,is_visible:true});if(ie)throw ie;redirectAfterSave()}
export async function updateSocialAction(f:FormData){await requireOwner();const id=idSchema.parse(value(f,'socialId'));const platform=z.string().trim().min(2).max(40).regex(/^[a-z0-9_-]+$/).parse(value(f,'platform').toLowerCase());const url=urlSchema.parse(value(f,'url'));const s=await createClient();const{error}=await s.from('social_links').update({platform,url,is_visible:f.get('isVisible')==='on'}).eq('id',id);if(error)throw error;redirectAfterSave()}
export async function deleteSocialAction(f:FormData){await requireOwner();const s=await createClient();const{error}=await s.from('social_links').delete().eq('id',idSchema.parse(value(f,'socialId')));if(error)throw error;redirectAfterSave()}
