'use server'

import { revalidatePath } from 'next/cache'
import { z } from 'zod'
import { createClient } from '@/lib/supabase/server'
import { getCurrentProfile, getCurrentUser } from '@/lib/auth/session'

const id=z.string().uuid()
const json=z.string().max(8000)
async function owner(){const user=await getCurrentUser();const profile=await getCurrentProfile();if(!user||!profile)throw new Error('Authentication required');return profile}
function done(){revalidatePath('/dashboard/edit');revalidatePath('/[username]','page')}
export async function saveDesignAdvanced(formData:FormData){const profile=await owner();const pageId=id.parse(String(formData.get('pageId')||''));const design=JSON.parse(json.parse(String(formData.get('design')||'{}')));const supabase=await createClient();const{data:page,error}=await supabase.from('pages').select('theme').eq('id',pageId).eq('profile_id',profile.id).maybeSingle();if(error||!page)throw error||new Error('Page not found');const current=page.theme&&typeof page.theme==='object'&&!Array.isArray(page.theme)?page.theme as Record<string,unknown>:{};const{error:updateError}=await supabase.from('pages').update({theme:{...current,...design}}).eq('id',pageId).eq('profile_id',profile.id);if(updateError)throw updateError;done()}
export async function applyTemplateAdvanced(formData:FormData){const profile=await owner();const pageId=id.parse(String(formData.get('pageId')||''));const template=z.enum(['minimal','creator','store','business','restaurant','services','luxury','bento']).parse(String(formData.get('template')||''));const presets={minimal:{theme:'mono',layout:'minimal'},creator:{theme:'midnight',layout:'creator'},store:{theme:'coral',layout:'store'},business:{theme:'paper',layout:'business'},restaurant:{theme:'forest',layout:'restaurant'},services:{theme:'ocean',layout:'services'},luxury:{theme:'sand',layout:'luxury'},bento:{theme:'violet',layout:'bento'}} as const;const supabase=await createClient();const{error}=await supabase.from('pages').update({theme:presets[template]}).eq('id',pageId).eq('profile_id',profile.id);if(error)throw error;done()}
export async function saveLinkAdvanced(formData:FormData){const profile=await owner();const linkId=id.parse(String(formData.get('linkId')||''));const style=JSON.parse(json.parse(String(formData.get('style')||'{}')));const imageUrl=String(formData.get('imageUrl')||'').trim()||null;const supabase=await createClient();const page=await supabase.from('pages').select('id').eq('profile_id',profile.id).maybeSingle();if(page.error||!page.data)throw page.error||new Error('Page not found');const section=await supabase.from('page_sections').select('id').eq('page_id',page.data.id);if(section.error)throw section.error;const ids=(section.data||[]).map(x=>x.id);if(!ids.length)throw new Error('Link not found');const{error}=await supabase.from('links').update({style,image_url:imageUrl}).eq('id',linkId).in('section_id',ids);if(error)throw error;done()}
export async function saveSectionAdvanced(formData:FormData){const profile=await owner();const sectionId=id.parse(String(formData.get('sectionId')||''));const style=JSON.parse(json.parse(String(formData.get('style')||'{}')));const supabase=await createClient();const page=await supabase.from('pages').select('id').eq('profile_id',profile.id).maybeSingle();if(page.error||!page.data)throw page.error||new Error('Page not found');const{error}=await supabase.from('page_sections').update({style}).eq('id',sectionId).eq('page_id',page.data.id);if(error)throw error;done()}
export async function saveSocialAdvanced(formData:FormData){const profile=await owner();const socialId=id.parse(String(formData.get('socialId')||''));const style=JSON.parse(json.parse(String(formData.get('style')||'{}')));const imageUrl=String(formData.get('imageUrl')||'').trim()||null;const supabase=await createClient();const page=await supabase.from('pages').select('id').eq('profile_id',profile.id).maybeSingle();if(page.error||!page.data)throw page.error||new Error('Page not found');const{error}=await supabase.from('social_links').update({style,image_url:imageUrl}).eq('id',socialId).eq('page_id',page.data.id);if(error)throw error;done()}
