'use client'

import { useMemo, useState, useTransition } from 'react'
import Image from 'next/image'
import { Check, ChevronDown, ExternalLink, ImagePlus, LayoutTemplate, Link2, Palette, Plus, Share2, Sparkles, Trash2, Upload, UserRound, X } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import { templates } from '@/components/public/template-data'
import { applyTemplateAction, saveDesignAction, updateLinkStyleAction, updatePageAction, updateSectionStyleAction, updateSocialStyleAction } from './actions'
import styles from './editor-studio.module.css'

type Tab='profile'|'content'|'social'|'design'|'templates'
type Theme='sand'|'midnight'|'violet'|'paper'|'forest'|'coral'|'ocean'|'mono'
type Layout='minimal'|'creator'|'store'|'business'|'restaurant'|'services'|'luxury'|'bento'

type Props={profile:any;page:any;sections:any[];socials:any[]}
const themeMeta:{id:Theme;name:string;bg:string;ink:string;accent:string}[]=[
 {id:'sand',name:'رملي',bg:'#f5eee2',ink:'#26221d',accent:'#c99d67'},
 {id:'midnight',name:'ليلي',bg:'#10151c',ink:'#f5f6f8',accent:'#8ea8ff'},
 {id:'violet',name:'بنفسجي',bg:'#f1ebfb',ink:'#292235',accent:'#9670cf'},
 {id:'paper',name:'ورقي',bg:'#faf9f4',ink:'#20251f',accent:'#9bad76'},
 {id:'forest',name:'غابة',bg:'#15251e',ink:'#f2f4ee',accent:'#a5c37b'},
 {id:'coral',name:'مرجاني',bg:'#fff0ec',ink:'#2a2020',accent:'#ed8c7c'},
 {id:'ocean',name:'محيط',bg:'#eaf4f6',ink:'#17262b',accent:'#6fa7b4'},
 {id:'mono',name:'أحادي',bg:'#f4f4f2',ink:'#191919',accent:'#777'},
]
const layouts:{id:Layout;name:string;desc:string}[]=[
 {id:'minimal',name:'هادئ',desc:'نظيف ومركّز'}, {id:'creator',name:'صانع محتوى',desc:'صورة وبطاقات بارزة'}, {id:'store',name:'متجر',desc:'منتجات أولاً'}, {id:'business',name:'أعمال',desc:'مرتب وموثوق'}, {id:'restaurant',name:'مطعم',desc:'صور وقائمة'}, {id:'services',name:'خدمات',desc:'حجوزات وتحويلات'}, {id:'luxury',name:'فاخر',desc:'مساحات أنيقة'}, {id:'bento',name:'مربعات',desc:'محتوى مرن'},
]
const socialPlatforms=['instagram','tiktok','youtube','x','facebook','linkedin','telegram','whatsapp','snapchat','github','website']

function initialDesign(page:any){const t=page?.theme&&typeof page.theme==='object'?page.theme:{};return {theme:(t.theme||'sand') as Theme,layout:(t.layout||'minimal') as Layout,background:t.background||'solid',backgroundColor:t.backgroundColor||'',font:t.font||'cairo',buttonStyle:t.buttonStyle||'soft',buttonRadius:Number(t.buttonRadius??18),buttonShadow:t.buttonShadow??true,cardOpacity:Number(t.cardOpacity??100),avatarShape:t.avatarShape||'circle',socialStyle:t.socialStyle||'icons',textAlign:t.textAlign||'center'}}

function UploadButton({label,onUploaded,folder}:{label:string;onUploaded:(url:string)=>void;folder:string}){
 const [busy,setBusy]=useState(false); const [error,setError]=useState('')
 async function choose(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setError('');if(!file.type.startsWith('image/')){setError('اختَر صورة فقط');return}if(file.size>6*1024*1024){setError('حجم الصورة يجب ألا يتجاوز 6MB');return}setBusy(true);try{const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('يجب تسجيل الدخول');const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${user.id}/${folder}/${crypto.randomUUID()}.${ext}`;const {error:uploadError}=await supabase.storage.from('imges').upload(path,file,{contentType:file.type,cacheControl:'31536000',upsert:false});if(uploadError)throw uploadError;const {data}=supabase.storage.from('imges').getPublicUrl(path);onUploaded(data.publicUrl)}catch(err){setError(err instanceof Error?err.message:'تعذر رفع الصورة')}finally{setBusy(false);e.target.value=''}}
 return <label className={styles.upload}>{busy?<span className={styles.spinner}/>:<Upload size={15}/>}<span>{busy?'جاري الرفع…':label}</span><input type="file" accept="image/*" onChange={choose} hidden/>{error&&<small>{error}</small>}</label>
}

function MiniPreview({theme,layout,title,username,bio,avatar,image,buttonStyle,avatarShape}:{theme:Theme;layout:Layout;title:string;username:string;bio:string;avatar?:string|null;image?:string;buttonStyle:string;avatarShape:string}){
 const tm=themeMeta.find(x=>x.id===theme)||themeMeta[0]; return <div className={`${styles.phone} ${styles[`phone_${layout}`]}`} style={{background:tm.bg,color:tm.ink}}><div className={styles.phoneTop}><span>لينكا</span><span>•••</span></div>{image&&<div className={styles.heroThumb} style={{backgroundImage:`url(${image})`}}/>}<div className={styles.phoneProfile}>{avatar?<Image src={avatar} alt="" width={58} height={58} className={avatarShape==='square'?styles.avatarSquare:styles.avatarCircle}/>:<div className={styles.avatarCircle}>{title.slice(0,1)}</div>}<strong>{title||'اسمك هنا'}</strong><small dir="ltr">@{username||'username'}</small>{bio&&<p>{bio}</p>}</div><div className={styles.previewSocials}><i/><i/><i/></div><div className={styles.previewLinks}><div className={`${styles.previewButton} ${styles[`button_${buttonStyle}`]}`}><span>الرابط الأول</span><b>↗</b></div><div className={`${styles.previewButton} ${styles[`button_${buttonStyle}`]}`}><span>رابط آخر</span><b>↗</b></div><div className={`${styles.previewButton} ${styles[`button_${buttonStyle}`]}`}><span>تواصل معي</span><b>↗</b></div></div></div>
}

export default function EditorStudio({profile,page,sections,socials}:Props){
 const [tab,setTab]=useState<Tab>('profile'); const [draft,setDraft]=useState({title:page?.title||'',username:profile.username||'',bio:page?.bio||'',seoTitle:page?.seo_title||'',seoDescription:page?.seo_description||'',avatarUrl:page?.avatar_url||profile.avatar_url||''});
 const [design,setDesign]=useState(initialDesign(page)); const [selectedSection,setSelectedSection]=useState<string|null>(sections[0]?.id||null); const [selectedLink,setSelectedLink]=useState<string|null>(sections.find(s=>s.type==='links')?.links?.[0]?.id||null); const [selectedSocial,setSelectedSocial]=useState<string|null>(socials[0]?.id||null); const [template,setTemplate]=useState<string>(''); const [notice,setNotice]=useState(''); const [pending,startTransition]=useTransition();
 const selectedLinkData=useMemo(()=>sections.flatMap(s=>s.links||[]).find(x=>x.id===selectedLink),[sections,selectedLink]);
 const selectedSectionData=sections.find(x=>x.id===selectedSection); const selectedSocialData=socials.find(x=>x.id===selectedSocial);
 function setField<K extends keyof typeof draft>(key:K,value:string){setDraft(x=>({...x,[key]:value}))}
 function savePage(){const fd=new FormData();fd.set('pageId',page.id);Object.entries(draft).forEach(([k,v])=>fd.set(k,v));fd.set('theme',design.theme);fd.set('layout',design.layout);startTransition(async()=>{try{await updatePageAction(fd)}catch(e){setNotice(e instanceof Error?e.message:'تعذر الحفظ')}})}
 function saveDesign(){const fd=new FormData();fd.set('pageId',page.id);fd.set('design',JSON.stringify(design));startTransition(async()=>{try{await saveDesignAction(fd);setNotice('تم حفظ التصميم')}catch(e){setNotice(e instanceof Error?e.message:'تعذر حفظ التصميم')}})}
 function applyTemplate(){if(!template)return;const t=templates.find(x=>x.id===template);if(!t)return;setDesign(d=>({...d,theme:t.theme,layout:t.layout}));const fd=new FormData();fd.set('pageId',page.id);fd.set('template',t.layout);startTransition(async()=>{try{await applyTemplateAction(fd);setNotice('تم تطبيق هوية القالب')}catch(e){setNotice(e instanceof Error?e.message:'تعذر تطبيق القالب')}})}
 async function saveLinkStyle(){if(!selectedLinkData)return;const fd=new FormData();fd.set('linkId',selectedLinkData.id);fd.set('imageUrl',selectedLinkData.image_url||'');fd.set('style',JSON.stringify(selectedLinkData.style||{}));try{await updateLinkStyleAction(fd);setNotice('تم حفظ تنسيق الرابط')}catch(e){setNotice(e instanceof Error?e.message:'تعذر الحفظ')}}
 async function saveSectionStyle(){if(!selectedSectionData)return;const fd=new FormData();fd.set('sectionId',selectedSectionData.id);fd.set('style',JSON.stringify(selectedSectionData.style||{}));try{await updateSectionStyleAction(fd);setNotice('تم حفظ تنسيق القسم')}catch(e){setNotice(e instanceof Error?e.message:'تعذر الحفظ')}}
 async function saveSocialStyle(){if(!selectedSocialData)return;const fd=new FormData();fd.set('socialId',selectedSocialData.id);fd.set('imageUrl',selectedSocialData.image_url||'');fd.set('style',JSON.stringify(selectedSocialData.style||{}));try{await updateSocialStyleAction(fd);setNotice('تم حفظ تنسيق الحساب')}catch(e){setNotice(e instanceof Error?e.message:'تعذر الحفظ')}}
 const tm=themeMeta.find(x=>x.id===design.theme)||themeMeta[0];
 return <main className={styles.root} dir="rtl">
  <header className={styles.topbar}><div className={styles.brand}><button onClick={()=>history.back()} aria-label="عودة">←</button><div><b>محرر لينكا</b><span>{pending?'جاري الحفظ…':notice||'كل شيء تحت سيطرتك'}</span></div></div><div className={styles.topActions}><a href={`/${draft.username}`} target="_blank" rel="noreferrer" className={styles.previewTop}><ExternalLink size={15}/> معاينة</a><button className={styles.publish} form="page-save">حفظ التغييرات</button></div></header>
  <div className={styles.workspace}>
   <aside className={styles.sidebar}><div className={styles.sidebarIntro}><Sparkles size={17}/><div><strong>صفحتك، بطريقتك</strong><small>صمّم ثم راقب النتيجة فوراً</small></div></div><nav>{([['profile','الهوية',UserRound],['content','المحتوى',Link2],['social','السوشال',Share2],['design','التصميم',Palette],['templates','القوالب',LayoutTemplate]] as const).map(([id,label,Icon])=><button key={id} className={tab===id?styles.active:''} onClick={()=>setTab(id)}><Icon size={17}/><span>{label}</span>{tab===id&&<i/>}</button>)}</nav><div className={styles.sidebarFoot}><span className={page.is_published?styles.dotGreen:styles.dot}/>{page.is_published?'الصفحة منشورة':'مسودة غير منشورة'}</div></aside>
   <section className={styles.panel}>
    {tab==='profile'&&<><PanelHead eyebrow="الهوية" title="من أنت؟" desc="اسمك، رابطك وصورتك — بدون روابط صور خارجية."/><div className={styles.formGrid}><Field label="اسم الصفحة" value={draft.title} onChange={v=>setField('title',v)} placeholder="مثلاً محمد دكارلي"/><div className={styles.urlField}><Field label="اسم المستخدم / الرابط" value={draft.username} onChange={v=>setField('username',v.toLowerCase().replace(/[^a-z0-9_-]/g,''))} placeholder="muhammed"/><span>linka.me/</span></div></div><div className={styles.avatarRow}><div className={styles.avatarBig}>{draft.avatarUrl?<Image src={draft.avatarUrl} alt="" width={78} height={78}/>:draft.title.slice(0,1)||'؟'}</div><div><b>صورة الملف الشخصي</b><p>JPG أو PNG أو WebP · حتى 6MB</p><div className={styles.row}><UploadButton label="رفع من الجهاز" folder="avatars" onUploaded={u=>setField('avatarUrl',u)}/>{draft.avatarUrl&&<button className={styles.textDanger} onClick={()=>setField('avatarUrl','')}><X size={14}/> إزالة</button>}</div></div></div><Field label="نبذة قصيرة" value={draft.bio} onChange={v=>setField('bio',v)} textarea placeholder="جملة أو جملتان تشرحان من أنت وما تقدمه…"/><details className={styles.advanced}><summary>SEO وإعدادات متقدمة <ChevronDown size={15}/></summary><div className={styles.formGrid}><Field label="عنوان SEO" value={draft.seoTitle} onChange={v=>setField('seoTitle',v)} placeholder={draft.title}/><Field label="وصف SEO" value={draft.seoDescription} onChange={v=>setField('seoDescription',v)} textarea/></div></details></>}
    {tab==='templates'&&<><PanelHead eyebrow="القوالب" title="ابدأ من تصميم جاهز" desc="شاهد الشكل قبل الاختيار. ويمكنك تعديل كل شيء بعد التطبيق."/><div className={styles.templateGrid}>{templates.map(t=><button key={t.id} className={`${styles.templateCard} ${template===t.id?styles.templateSelected:''}`} onClick={()=>setTemplate(t.id)}><MiniPreview theme={t.theme} layout={t.layout} title={t.title} username={t.handle.replace('@','')} bio={t.bio} avatar={undefined} image={t.heroImage} buttonStyle="soft" avatarShape="circle"/><div className={styles.templateMeta}><strong>{t.name}</strong><span>{t.category}</span></div>{template===t.id&&<span className={styles.templateCheck}><Check size={14}/></span>}</button>)}</div><div className={styles.stickySave}><span>{template?'تم اختيار قالب':'اختر قالباً لرؤية الخيارات'}</span><button className={styles.primary} disabled={!template||pending} onClick={applyTemplate}>{pending?'جاري التطبيق…':'تطبيق القالب'}</button></div></>}
    {tab==='design'&&<><PanelHead eyebrow="التصميم" title="خلّي الصفحة تشبهك" desc="الألوان والأزرار والخلفية والشكل كلها قابلة للتخصيص."/><SectionTitle title="الهوية البصرية"/><div className={styles.themeGrid}>{themeMeta.map(t=><button key={t.id} onClick={()=>setDesign(d=>({...d,theme:t.id}))} className={design.theme===t.id?styles.themeSelected:''} style={{background:t.bg,color:t.ink}}><span style={{background:t.accent}}/>{t.name}{design.theme===t.id&&<Check size={14}/>}</button>)}</div><SectionTitle title="تخطيط الصفحة"/><div className={styles.layoutGrid}>{layouts.map(l=><button key={l.id} className={design.layout===l.id?styles.layoutSelected:''} onClick={()=>setDesign(d=>({...d,layout:l.id}))}><strong>{l.name}</strong><small>{l.desc}</small></button>)}</div><SectionTitle title="شكل الأزرار"/><div className={styles.choiceGrid}>{['soft','pill','square','outline','glass'].map(x=><button key={x} className={design.buttonStyle===x?styles.choiceSelected:''} onClick={()=>setDesign(d=>({...d,buttonStyle:x}))}><span className={`${styles.demoButton} ${styles[`button_${x}`]}`}>رابط</span><small>{{soft:'ناعم',pill:'كبسولة',square:'مربع',outline:'إطار',glass:'زجاجي'}[x as string]}</small></button>)}</div><div className={styles.twoCols}><Choice label="شكل الصورة" value={design.avatarShape} options={['circle','square']} labels={['دائرية','مربعة']} onChange={v=>setDesign(d=>({...d,avatarShape:v}))}/><Choice label="محاذاة النص" value={design.textAlign} options={['center','right']} labels={['وسط','يمين']} onChange={v=>setDesign(d=>({...d,textAlign:v}))}/></div><div className={styles.saveBar}><button className={styles.primary} onClick={saveDesign} disabled={pending}>{pending?'جاري الحفظ…':'حفظ التصميم'}</button></div></>}
    {tab==='content'&&<><PanelHead eyebrow="المحتوى" title="رتّب ما تريد أن يراه الزائر" desc="اختر عنصراً وعدّل مظهره. الإضافة والحذف وإعادة الترتيب تبقى من النظام الحالي."/><div className={styles.contentList}>{sections.map((s,i)=><div key={s.id} className={selectedSection===s.id?styles.contentCardSelected:styles.contentCard}><button className={styles.contentHead} onClick={()=>setSelectedSection(selectedSection===s.id?null:s.id)}><span className={styles.drag}>⠿</span><span><b>{s.title||({links:'روابط',products:'منتجات',services:'خدمات'} as any)[s.type]||s.type}</b><small>{(s.links||s.products||s.services||[]).length} عناصر</small></span><ChevronDown size={17}/></button>{selectedSection===s.id&&<div className={styles.contentBody}>{s.type==='links'&&(s.links||[]).map((l:any)=><div key={l.id} className={selectedLink===l.id?styles.itemSelected:styles.item} onClick={()=>setSelectedLink(l.id)}><div><b>{l.title}</b><small>{l.url}</small></div><span>تخصيص</span></div>)}<div className={styles.inlineStyle}><SectionTitle title="مظهر القسم"/><div className={styles.choiceGrid}>{['plain','card','soft','glass'].map(x=><button key={x} className={(s.style?.variant||'plain')===x?styles.choiceSelected:''} onClick={()=>{s.style={...(s.style||{}),variant:x};setSelectedSection(s.id)}}>{x==='plain'?'بسيط':x==='card'?'بطاقة':x==='soft'?'ناعم':'زجاجي'}</button>)}</div><button className={styles.secondary} onClick={saveSectionStyle}>حفظ مظهر القسم</button></div></div>}</div>)}<div className={styles.addBlock}><Plus size={17}/><b>إضافة قسم جديد</b><small>الأنواع المتاحة حالياً: روابط، منتجات، خدمات</small></div></div>{selectedLinkData&&<div className={styles.itemEditor}><SectionTitle title={`تخصيص: ${selectedLinkData.title}`}/><Field label="عنوان الرابط" value={selectedLinkData.title} onChange={v=>{selectedLinkData.title=v}}/><div className={styles.formGrid}><Field label="الشكل" value={selectedLinkData.style?.variant||'soft'} onChange={v=>{selectedLinkData.style={...(selectedLinkData.style||{}),variant:v}}}/><Field label="عرض الزر" value={selectedLinkData.style?.width||'full'} onChange={v=>{selectedLinkData.style={...(selectedLinkData.style||{}),width:v}}}/></div><div className={styles.avatarRow}><div className={styles.thumb}>{selectedLinkData.image_url?<Image src={selectedLinkData.image_url} alt="" width={52} height={52}/>:<ImagePlus size={20}/>}</div><UploadButton label="صورة / أيقونة للرابط" folder="links" onUploaded={u=>{selectedLinkData.image_url=u}}/><button className={styles.primarySmall} onClick={saveLinkStyle}>حفظ تخصيص الرابط</button></div></div>}</>}
    {tab==='social'&&<><PanelHead eyebrow="السوشال" title="خلي حساباتك واضحة" desc="أيقونات مرتبة، صور اختيارية، وروابط سهلة الفهم."/><div className={styles.socialList}>{socials.map((s:any)=><button key={s.id} className={selectedSocial===s.id?styles.socialSelected:styles.socialCard} onClick={()=>setSelectedSocial(s.id)}><span className={styles.socialIcon}>{s.image_url?<Image src={s.image_url} alt="" width={34} height={34}/>:s.platform.slice(0,1).toUpperCase()}</span><span><b>{s.platform}</b><small>{s.url}</small></span><ChevronDown size={16}/></button>)}</div>{selectedSocialData&&<div className={styles.itemEditor}><SectionTitle title={`تخصيص ${selectedSocialData.platform}`}/><Field label="المنصة" value={selectedSocialData.platform} onChange={v=>selectedSocialData.platform=v}/><div className={styles.avatarRow}><div className={styles.thumb}>{selectedSocialData.image_url?<Image src={selectedSocialData.image_url} alt="" width={52} height={52}/>:<Share2 size={20}/>}</div><UploadButton label="إضافة صورة للحساب" folder="social" onUploaded={u=>{selectedSocialData.image_url=u}}/><button className={styles.primarySmall} onClick={saveSocialStyle}>حفظ التخصيص</button></div></div>}<div className={styles.addBlock}><Plus size={17}/><b>إضافة حساب اجتماعي</b><small>{socialPlatforms.join(' · ')}</small></div></>}
   </section>
   <aside className={styles.previewPane}><div className={styles.previewHeader}><div><b>معاينة مباشرة</b><small>تحديث بصري أثناء التعديل</small></div><span>● LIVE</span></div><div className={styles.previewStage} style={{background:design.background==='gradient'?`linear-gradient(135deg, ${tm.bg}, ${tm.accent}55)`:tm.bg}}><MiniPreview theme={design.theme} layout={design.layout} title={draft.title} username={draft.username} bio={draft.bio} avatar={draft.avatarUrl} image={undefined} buttonStyle={design.buttonStyle} avatarShape={design.avatarShape}/></div><div className={styles.urlPreview}><span>رابط صفحتك</span><strong dir="ltr">linka.me/{draft.username||'username'}</strong></div></aside>
  </div><form id="page-save" action={async()=>savePage()}><input type="hidden"/></form>
 </main>
}
function PanelHead({eyebrow,title,desc}:{eyebrow:string;title:string;desc:string}){return <div className={styles.panelHead}><span>{eyebrow}</span><h1>{title}</h1><p>{desc}</p></div>}
function SectionTitle({title}:{title:string}){return <div className={styles.sectionTitle}><b>{title}</b></div>}
function Field({label,value,onChange,placeholder,textarea=false}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;textarea?:boolean}){return <label className={styles.field}><span>{label}</span>{textarea?<textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} rows={4}/>:<input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>}</label>}
function Choice({label,value,options,labels,onChange}:{label:string;value:string;options:string[];labels:string[];onChange:(v:string)=>void}){return <div className={styles.choiceBlock}><span>{label}</span><div>{options.map((x,i)=><button key={x} className={value===x?styles.choiceSelected:''} onClick={()=>onChange(x)}>{labels[i]}</button>)}</div></div>}
