import Link from 'next/link'
import { ArrowDown, ArrowUp, ExternalLink, Plus, Trash2 } from 'lucide-react'
import { getCurrentProfile } from '@/lib/auth/session'
import { getPage } from '@/lib/db/pages'
import { getSections } from '@/lib/db/sections'
import { createClient } from '@/lib/supabase/server'
import styles from './editor.module.css'
import {
  addLinkAction, addProductAction, addSectionAction, addServiceAction, addSocialAction,
  createPageAction, deleteLinkAction, deleteProductAction, deleteSectionAction, deleteServiceAction, deleteSocialAction,
  moveLinkAction, moveProductAction, moveSectionAction, moveServiceAction,
  togglePublishAction, updateLinkAction, updatePageAction, updateProductAction, updateSectionAction, updateServiceAction, updateSocialAction,
} from './actions'

const themes = ['sand', 'midnight', 'violet', 'paper', 'forest', 'coral', 'ocean', 'mono'] as const
const layouts = ['minimal', 'creator', 'store', 'business', 'restaurant', 'services', 'luxury', 'bento'] as const
const sectionTypes = [['links', 'روابط'], ['products', 'منتجات'], ['services', 'خدمات'], ['social', 'شبكات التواصل'], ['text', 'نص'], ['media', 'وسائط']] as const

function Field({ label, name, defaultValue = '', type = 'text', placeholder = '' }: { label: string; name: string; defaultValue?: string | number | null; type?: string; placeholder?: string }) { return <label className="editor-field"><span>{label}</span><input name={name} type={type} defaultValue={defaultValue ?? ''} placeholder={placeholder} /></label> }
function Actions({ up, down, action, idName, id }: { up?: boolean; down?: boolean; action: (formData: FormData) => void; idName: string; id: string }) { return <form action={action} className="editor-inline-actions"><input type="hidden" name={idName} value={id}/>{up && <button name="direction" value="up" title="للأعلى" aria-label="للأعلى"><ArrowUp size={15}/></button>}{down && <button name="direction" value="down" title="للأسفل" aria-label="للأسفل"><ArrowDown size={15}/></button>}</form> }

export default async function EditPage() {
  const profile = await getCurrentProfile()
  if (!profile) return null
  const page = await getPage(profile.id)
  const sections = page ? await getSections(page.id) : []
  const supabase = await createClient()
  const { data: socials } = page ? await supabase.from('social_links').select('*').eq('page_id', page.id).order('position') : { data: [] }

  return <main className={`${styles.root} editor-page`} dir="rtl">
    <header className="editor-header"><div><Link href="/dashboard" className="editor-back">← لوحة التحكم</Link><p className="eyebrow">محرر لينكا</p><h1>{page ? 'حرّر صفحتك كما تريد.' : 'أنشئ صفحتك الأولى.'}</h1><p>كل تعديل يمر عبر صلاحيات حسابك وحدود باقتك قبل حفظه.</p></div>{page && <div className="editor-header-actions"><Link className="editor-secondary" href={`/${profile.username}`} target="_blank">معاينة <ExternalLink size={16}/></Link><form action={togglePublishAction}><input type="hidden" name="pageId" value={page.id}/><button className="editor-primary" type="submit">{page.is_published ? 'إلغاء النشر' : 'نشر الصفحة'}</button></form></div>}</header>
    {!page ? <section className="editor-card editor-create-card"><h2>ابدأ الآن</h2><p>سيتم إنشاء صفحة خاصة بحسابك، ثم يمكنك إضافة الروابط والأقسام والمنتجات والخدمات.</p><form action={createPageAction} className="editor-form"><Field label="عنوان الصفحة" name="title" placeholder="مثلاً: محمد دكارلي"/><button className="editor-primary" type="submit"><Plus size={17}/> إنشاء الصفحة</button></form></section> : <>
      <section className="editor-card"><div className="editor-card-title"><div><p className="eyebrow">الهوية وSEO</p><h2>معلومات الصفحة</h2></div><span className={page.is_published ? 'editor-badge success' : 'editor-badge'}>{page.is_published ? 'منشورة' : 'مسودة'}</span></div><form action={updatePageAction} className="editor-form"><input type="hidden" name="pageId" value={page.id}/><div className="editor-grid"><Field label="العنوان" name="title" defaultValue={page.title}/><Field label="رابط الصورة" name="avatarUrl" defaultValue={page.avatar_url} placeholder="https://..."/></div><Field label="نبذة" name="bio" defaultValue={page.bio}/><div className="editor-grid"><Field label="عنوان SEO" name="seoTitle" defaultValue={page.seo_title}/><Field label="وصف SEO" name="seoDescription" defaultValue={page.seo_description}/></div><div className="editor-grid"><label className="editor-field"><span>الثيم</span><select name="theme" defaultValue={String((page.theme as Record<string, unknown>)?.theme ?? 'sand')}>{themes.map((theme)=><option key={theme} value={theme}>{theme}</option>)}</select></label><label className="editor-field"><span>التخطيط</span><select name="layout" defaultValue={String((page.theme as Record<string, unknown>)?.layout ?? 'minimal')}>{layouts.map((layout)=><option key={layout} value={layout}>{layout}</option>)}</select></label></div><button className="editor-primary" type="submit">حفظ المعلومات</button></form></section>
      <section className="editor-card"><div className="editor-card-title"><div><p className="eyebrow">أقسام الصفحة</p><h2>المحتوى</h2></div><span className="editor-muted">الخطة: {profile.plan_type}</span></div><form action={addSectionAction} className="editor-add-row"><select name="type" defaultValue="links">{sectionTypes.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input name="title" placeholder="اسم القسم (اختياري)"/><button className="editor-primary" type="submit"><Plus size={16}/> إضافة قسم</button></form><div className="editor-sections">{sections.map((section,index)=><article className="editor-section" key={section.id}><div className="editor-section-heading"><form action={updateSectionAction} className="editor-section-name"><input type="hidden" name="sectionId" value={section.id}/><input name="title" defaultValue={section.title ?? ''} placeholder="عنوان القسم"/><label><input name="isVisible" type="checkbox" defaultChecked={section.is_visible}/> ظاهر</label><button type="submit">حفظ</button></form><div className="editor-section-tools"><Actions action={moveSectionAction} idName="sectionId" id={section.id} up={index>0} down={index<sections.length-1}/><form action={deleteSectionAction}><input type="hidden" name="sectionId" value={section.id}/><button className="editor-danger-icon" title="حذف القسم" aria-label="حذف القسم"><Trash2 size={15}/></button></form></div></div>
        {section.type==='links' && <><div className="editor-items">{('links' in section ? section.links : []).map((item: any,itemIndex:number,arr:any[])=> <div className="editor-item" key={item.id}><form action={updateLinkAction} className="editor-item-form"><input type="hidden" name="linkId" value={item.id}/><Field label="العنوان" name="title" defaultValue={item.title}/><Field label="الرابط" name="url" defaultValue={item.url}/><label className="editor-check"><input name="isVisible" type="checkbox" defaultChecked={item.is_visible}/> ظاهر</label><button type="submit">حفظ</button></form><div><Actions action={moveLinkAction} idName="linkId" id={item.id} up={itemIndex>0} down={itemIndex<arr.length-1}/><form action={deleteLinkAction}><input type="hidden" name="linkId" value={item.id}/><button className="editor-danger-icon" title="حذف" aria-label="حذف"><Trash2 size={15}/></button></form></div></div>)}</div><form action={addLinkAction} className="editor-add-subform"><input type="hidden" name="sectionId" value={section.id}/><Field label="عنوان الرابط" name="title"/><Field label="الرابط" name="url" placeholder="https://..."/><button className="editor-secondary" type="submit"><Plus size={15}/> إضافة رابط</button></form></>}
        {section.type==='products' && <><div className="editor-items">{('products' in section ? section.products : []).map((item:any,itemIndex:number,arr:any[])=> <div className="editor-item" key={item.id}><form action={updateProductAction} className="editor-item-form"><input type="hidden" name="productId" value={item.id}/><Field label="الاسم" name="name" defaultValue={item.name}/><Field label="السعر بالسنت" name="priceCents" type="number" defaultValue={item.price_cents}/><Field label="العملة" name="currency" defaultValue={item.currency}/><Field label="رابط الشراء" name="checkoutUrl" defaultValue={item.checkout_url}/><Field label="واتساب" name="whatsappNumber" defaultValue={item.whatsapp_number}/><label className="editor-check"><input name="isVisible" type="checkbox" defaultChecked={item.is_visible}/> ظاهر</label><button type="submit">حفظ</button></form><div><Actions action={moveProductAction} idName="productId" id={item.id} up={itemIndex>0} down={itemIndex<arr.length-1}/><form action={deleteProductAction}><input type="hidden" name="productId" value={item.id}/><button className="editor-danger-icon" title="حذف" aria-label="حذف"><Trash2 size={15}/></button></form></div></div>)}</div><form action={addProductAction} className="editor-add-subform"><input type="hidden" name="sectionId" value={section.id}/><Field label="اسم المنتج" name="name"/><Field label="السعر بالسنت" name="priceCents" type="number"/><Field label="العملة" name="currency" defaultValue="USD"/><Field label="رابط الشراء" name="checkoutUrl"/><Field label="واتساب" name="whatsappNumber"/><button className="editor-secondary" type="submit"><Plus size={15}/> إضافة منتج</button></form></>}
        {section.type==='services' && <><div className="editor-items">{('services' in section ? section.services : []).map((item:any,itemIndex:number,arr:any[])=> <div className="editor-item" key={item.id}><form action={updateServiceAction} className="editor-item-form"><input type="hidden" name="serviceId" value={item.id}/><Field label="الاسم" name="name" defaultValue={item.name}/><Field label="الوصف" name="description" defaultValue={item.description}/><Field label="السعر بالسنت" name="priceCents" type="number" defaultValue={item.price_cents}/><Field label="المدة بالدقائق" name="durationMinutes" type="number" defaultValue={item.duration_minutes}/><Field label="الحجز" name="bookingUrl" defaultValue={item.booking_url}/><Field label="واتساب" name="whatsappNumber" defaultValue={item.whatsapp_number}/><label className="editor-check"><input name="isVisible" type="checkbox" defaultChecked={item.is_visible}/> ظاهر</label><button type="submit">حفظ</button></form><div><Actions action={moveServiceAction} idName="serviceId" id={item.id} up={itemIndex>0} down={itemIndex<arr.length-1}/><form action={deleteServiceAction}><input type="hidden" name="serviceId" value={item.id}/><button className="editor-danger-icon" title="حذف" aria-label="حذف"><Trash2 size={15}/></button></form></div></div>)}</div><form action={addServiceAction} className="editor-add-subform"><input type="hidden" name="sectionId" value={section.id}/><Field label="اسم الخدمة" name="name"/><Field label="الوصف" name="description"/><Field label="السعر بالسنت" name="priceCents" type="number"/><Field label="المدة بالدقائق" name="durationMinutes" type="number"/><Field label="الحجز" name="bookingUrl"/><Field label="واتساب" name="whatsappNumber"/><Field label="العملة" name="currency" defaultValue="USD"/><button className="editor-secondary" type="submit"><Plus size={15}/> إضافة خدمة</button></form></>}
        {section.type!=='links' && section.type!=='products' && section.type!=='services' && <div className="editor-placeholder">قسم <strong>{section.type}</strong> موجود، لكن هذا النوع يحتاج محررًا متخصصًا.</div>}
      </article>)}</div></section>
      <section className="editor-card"><div className="editor-card-title"><div><p className="eyebrow">التواصل</p><h2>روابط التواصل الاجتماعي</h2></div></div><div className="editor-items">{(socials ?? []).map((item:any)=><div className="editor-item" key={item.id}><form action={updateSocialAction} className="editor-item-form"><input type="hidden" name="socialId" value={item.id}/><Field label="المنصة" name="platform" defaultValue={item.platform}/><Field label="الرابط" name="url" defaultValue={item.url}/><label className="editor-check"><input name="isVisible" type="checkbox" defaultChecked={item.is_visible}/> ظاهر</label><button type="submit">حفظ</button></form><form action={deleteSocialAction}><input type="hidden" name="socialId" value={item.id}/><button className="editor-danger-icon" title="حذف" aria-label="حذف"><Trash2 size={15}/></button></form></div>)}</div><form action={addSocialAction} className="editor-add-subform"><Field label="المنصة" name="platform" placeholder="instagram"/><Field label="الرابط" name="url" placeholder="https://..."/><button className="editor-secondary" type="submit"><Plus size={15}/> إضافة حساب</button></form></section>
    </>}
  </main>
}
