import Link from "next/link";
import { Check, Lock, Sparkles } from "lucide-react";
import { CheckoutButton } from "@/components/billing/checkout-button";
import { MarketingHeader } from "@/components/public/marketing-header";

const plans = [
  { name: "Free", price: "$0", description: "صفحة حقيقية ومفيدة بدون دفع، لتبدأ وتثبت فكرتك.", features: ["10 روابط", "3 أقسام", "منتج واحد + خدمة واحدة", "كل الأيقونات الاجتماعية", "8 قوالب أساسية", "معاينة مباشرة", "رفع صورة من الجهاز"], locked: ["تحليلات متقدمة", "QR Code", "SEO المتقدم", "النطاق المخصص", "الجدولة", "إزالة علامة لينكا"], action: "ابدأ مجاناً" },
  { name: "Pro", price: "$29", description: "للمبدعين الذين يريدون تحويل الصفحة إلى قناة نمو وبيع.", features: ["كل ما في Free", "روابط وأقسام ومنتجات وخدمات بلا حدود", "تحليلات متقدمة", "QR Code", "SEO وبيانات المشاركة", "نطاق مخصص", "تصميم وخطوط وخلفيات متقدمة", "إزالة علامة لينكا", "جدولة الروابط", "تصدير البيانات"], locked: ["دعم أولوية", "ميزات فرق الأعمال"], action: "pro" },
  { name: "Business", price: "$79", description: "للشركات والفرق التي تحتاج تحكماً ونمواً ودعماً أعلى.", features: ["كل مزايا Pro", "دعم ذو أولوية", "Newsletter بدون حد", "Pixels وUTM", "إدارة حملات ونمو متقدم", "سعة غير محدودة"], locked: [], action: "business" },
] as const;

export default function PricingPage() {
 return <div className="pricing-page"><MarketingHeader/><main id="main-content" className="pricing-main"><header className="pricing-heading"><p className="eyebrow"><Sparkles size={15} className="inline"/> خطط مصممة للنمو</p><h1>ابدأ مجاناً.<br/>ادفع فقط عندما تحتاج المزيد.</h1><p>النسخة المجانية ليست تجربة ناقصة: ابنِ صفحة كاملة وابدأ بجمهورك. عندما تحتاج التحليلات، البيع المتقدم، النطاق والتخصيص الاحترافي، انتقل إلى Pro.</p></header><section className="pricing-grid" aria-label="خطط الاشتراك">{plans.map(plan=><article className={`pricing-card ${plan.name==='Pro'?'featured':''}`} key={plan.name}>{plan.name==='Pro'&&<span className="plan-tag">الأكثر اختياراً</span>}<h2>{plan.name}</h2><p className="plan-description">{plan.description}</p><p className="plan-price"><strong>{plan.price}</strong>{plan.price!=="$0"&&<span> / شهرياً</span>}</p><ul>{plan.features.map(feature=><li key={feature}><Check size={16} aria-hidden="true"/>{feature}</li>)}</ul>{plan.locked.length>0&&<div className="mt-4 border-t pt-4"><p className="mb-2 text-xs font-bold text-slate-500">مقفول حتى الترقية</p><ul>{plan.locked.map(feature=><li key={feature} className="opacity-60"><Lock size={14}/>{feature}</li>)}</ul></div>}{plan.action==='ابدأ مجاناً'?<Link className="pricing-action" href="/signup">ابدأ مجاناً</Link>:<CheckoutButton plan={plan.action}/>}</article>)}</section><div className="pricing-note">لا نستخدم القيود لإجبارك على الدفع؛ نستخدم الميزات المتقدمة لتجعل الترقية منطقية عندما تبدأ الصفحة بتحقيق نتائج.</div></main></div>;
}
